spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/auth_db?authSource=admin
  web:
    cors:
      allowed-origins: http://localhost:3000,http://localhost:5173,http://localhost:5174
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

server:
  port: 8085

# JWT Configuration
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
